name: Static Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'AlexAlgarate/wedding_miguel_patri'
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    env:
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      PATRI_PHONE: ${{ secrets.PATRI_PHONE }}
      MIGUEL_PHONE: ${{ secrets.MIGUEL_PHONE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run build script
        run: |
          chmod +x ./remote_build.sh
          ./remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build for Vercel
          commit_user_name: Alex Algarate [GitHub Actions]
          commit_user_email: alex.algarate@gmail.com
          commit_author: AlexAlgarate <alex.algarate@gmail.com>
